<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>

        <OutputType>Library</OutputType>
        <PublishAot>true</PublishAot>

        <StripSymbols>true</StripSymbols>


        <IsAotCompatible>true</IsAotCompatible>
    </PropertyGroup>

    <PropertyGroup Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android' Or $(RuntimeIdentifier.StartsWith('android-'))">
        <DefineConstants>$(DefineConstants);ANDROID</DefineConstants>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\Libraries\KuGou.Net\KuGou.Net.csproj"/>
    </ItemGroup>

</Project>
