<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net11.0</TargetFramework>
    <Features>$(Features);runtime-async=on</Features>
    <Nullable>enable</Nullable>
    <AssemblyName>AvaloniaLyrics</AssemblyName>
    <PackageId>AvaloniaLyrics</PackageId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" />
    <PackageReference Include="ZLinq" />
  </ItemGroup>
</Project>
